/*
 * Minimal stand-in for XC8's <xc.h> (PIC18F4525) so the power board
 * firmware can be checked with a host compiler (make check / make link) and
 * replayed against recordings of the original binary (make difftest).
 *
 * Every SFR lives in pic_sfr[], indexed by its real address - 0xF80, so a
 * snapshot of the chip's SFR page can be loaded with one memcpy. Not a
 * simulator: nothing happens when a register is written.
 */
#ifndef HOST_XC_H
#define HOST_XC_H
#include <stdint.h>

#define __interrupt(...)
#define asm(x) ((void)0)
#define NOP() ((void)0)
#define CLRWDT() ((void)0)
#define SLEEP() ((void)0)
#define RESET() ((void)0)
#define di() (INTCONbits.GIE = 0)
#define ei() (INTCONbits.GIE = 1)

extern volatile uint8_t pic_sfr[0x80];
#define PIC_SFR(a) (pic_sfr[(a) - 0xF80])

#define PORTA     PIC_SFR(0xF80)
#define PORTB     PIC_SFR(0xF81)
#define PORTC     PIC_SFR(0xF82)
#define PORTD     PIC_SFR(0xF83)
#define PORTE     PIC_SFR(0xF84)
#define LATA      PIC_SFR(0xF89)
#define LATB      PIC_SFR(0xF8A)
#define LATC      PIC_SFR(0xF8B)
#define LATD      PIC_SFR(0xF8C)
#define LATE      PIC_SFR(0xF8D)
#define TRISA     PIC_SFR(0xF92)
#define TRISB     PIC_SFR(0xF93)
#define TRISC     PIC_SFR(0xF94)
#define TRISD     PIC_SFR(0xF95)
#define TRISE     PIC_SFR(0xF96)
#define OSCTUNE   PIC_SFR(0xF9B)
#define PIE1      PIC_SFR(0xF9D)
#define PIR1      PIC_SFR(0xF9E)
#define IPR1      PIC_SFR(0xF9F)
#define PIE2      PIC_SFR(0xFA0)
#define PIR2      PIC_SFR(0xFA1)
#define IPR2      PIC_SFR(0xFA2)
#define EECON1    PIC_SFR(0xFA6)
#define EECON2    PIC_SFR(0xFA7)
#define EEDATA    PIC_SFR(0xFA8)
#define EEADR     PIC_SFR(0xFA9)
#define EEADRH    PIC_SFR(0xFAA)
#define RCSTA     PIC_SFR(0xFAB)
#define TXSTA     PIC_SFR(0xFAC)
#define TXREG     PIC_SFR(0xFAD)
#define RCREG     PIC_SFR(0xFAE)
#define SPBRG     PIC_SFR(0xFAF)
#define SPBRGH    PIC_SFR(0xFB0)
#define T3CON     PIC_SFR(0xFB1)
#define TMR3L     PIC_SFR(0xFB2)
#define TMR3H     PIC_SFR(0xFB3)
#define CMCON     PIC_SFR(0xFB4)
#define CVRCON    PIC_SFR(0xFB5)
#define BAUDCON   PIC_SFR(0xFB8)
#define CCP2CON   PIC_SFR(0xFBA)
#define CCPR2L    PIC_SFR(0xFBB)
#define CCPR2H    PIC_SFR(0xFBC)
#define CCP1CON   PIC_SFR(0xFBD)
#define CCPR1L    PIC_SFR(0xFBE)
#define CCPR1H    PIC_SFR(0xFBF)
#define ADCON2    PIC_SFR(0xFC0)
#define ADCON1    PIC_SFR(0xFC1)
#define ADCON0    PIC_SFR(0xFC2)
#define ADRESL    PIC_SFR(0xFC3)
#define ADRESH    PIC_SFR(0xFC4)
#define SSPCON2   PIC_SFR(0xFC5)
#define SSPCON1   PIC_SFR(0xFC6)
#define SSPSTAT   PIC_SFR(0xFC7)
#define SSPADD    PIC_SFR(0xFC8)
#define SSPBUF    PIC_SFR(0xFC9)
#define T2CON     PIC_SFR(0xFCA)
#define PR2       PIC_SFR(0xFCB)
#define TMR2      PIC_SFR(0xFCC)
#define T1CON     PIC_SFR(0xFCD)
#define TMR1L     PIC_SFR(0xFCE)
#define TMR1H     PIC_SFR(0xFCF)
#define RCON      PIC_SFR(0xFD0)
#define WDTCON    PIC_SFR(0xFD1)
#define HLVDCON   PIC_SFR(0xFD2)
#define OSCCON    PIC_SFR(0xFD3)
#define T0CON     PIC_SFR(0xFD5)
#define TMR0L     PIC_SFR(0xFD6)
#define TMR0H     PIC_SFR(0xFD7)
#define STATUS    PIC_SFR(0xFD8)
#define BSR       PIC_SFR(0xFE0)
#define WREG      PIC_SFR(0xFE8)
#define INTCON3   PIC_SFR(0xFF0)
#define INTCON2   PIC_SFR(0xFF1)
#define INTCON    PIC_SFR(0xFF2)
#define PRODL     PIC_SFR(0xFF3)
#define PRODH     PIC_SFR(0xFF4)
#define TABLAT    PIC_SFR(0xFF5)
#define TBLPTRL   PIC_SFR(0xFF6)
#define TBLPTRH   PIC_SFR(0xFF7)
#define TBLPTRU   PIC_SFR(0xFF8)

#define PIC_SFR16(lo) (*(volatile uint16_t *)&PIC_SFR(lo))       /* little-endian host */
#define TMR0  PIC_SFR16(0xFD6)
#define TMR1  PIC_SFR16(0xFCE)
#define TMR3  PIC_SFR16(0xFB2)
#define CCPR1 PIC_SFR16(0xFBE)
#define ADRES PIC_SFR16(0xFC3)

#define PIC_BITS(reg, ...) (*(volatile struct { unsigned __VA_ARGS__; } *)&reg)
#define PORTAbits PIC_BITS(PORTA, RA0:1, RA1:1, RA2:1, RA3:1, RA4:1, RA5:1, RA6:1, RA7:1)
#define PORTBbits PIC_BITS(PORTB, RB0:1, RB1:1, RB2:1, RB3:1, RB4:1, RB5:1, RB6:1, RB7:1)
#define PORTCbits PIC_BITS(PORTC, RC0:1, RC1:1, RC2:1, RC3:1, RC4:1, RC5:1, RC6:1, RC7:1)
#define PORTDbits PIC_BITS(PORTD, RD0:1, RD1:1, RD2:1, RD3:1, RD4:1, RD5:1, RD6:1, RD7:1)
#define PORTEbits PIC_BITS(PORTE, RE0:1, RE1:1, RE2:1, RE3:1, :4)
#define LATBbits PIC_BITS(LATB, LATB0:1, LATB1:1, LATB2:1, LATB3:1, LATB4:1, LATB5:1, LATB6:1, LATB7:1)
#define LATDbits PIC_BITS(LATD, LATD0:1, LATD1:1, LATD2:1, LATD3:1, LATD4:1, LATD5:1, LATD6:1, LATD7:1)
#define INTCONbits PIC_BITS(INTCON, RBIF:1, INT0IF:1, TMR0IF:1, RBIE:1, INT0IE:1, TMR0IE:1, PEIE:1, GIE:1)
#define PIR1bits PIC_BITS(PIR1, TMR1IF:1, TMR2IF:1, CCP1IF:1, SSPIF:1, TXIF:1, RCIF:1, ADIF:1, PSPIF:1)
#define PIR2bits PIC_BITS(PIR2, CCP2IF:1, TMR3IF:1, HLVDIF:1, BCLIF:1, EEIF:1, :1, CMIF:1, OSCFIF:1)
#define PIE1bits PIC_BITS(PIE1, TMR1IE:1, TMR2IE:1, CCP1IE:1, SSPIE:1, TXIE:1, RCIE:1, ADIE:1, PSPIE:1)
#define PIE2bits PIC_BITS(PIE2, CCP2IE:1, TMR3IE:1, HLVDIE:1, BCLIE:1, EEIE:1, :1, CMIE:1, OSCFIE:1)
#define RCONbits PIC_BITS(RCON, NOT_BOR:1, NOT_POR:1, NOT_PD:1, NOT_TO:1, NOT_RI:1, :1, SBOREN:1, IPEN:1)
#define T0CONbits PIC_BITS(T0CON, T0PS0:1, T0PS1:1, T0PS2:1, PSA:1, T0SE:1, T0CS:1, T08BIT:1, TMR0ON:1)
#define T1CONbits PIC_BITS(T1CON, TMR1ON:1, TMR1CS:1, NOT_T1SYNC:1, T1OSCEN:1, T1CKPS0:1, T1CKPS1:1, T1RUN:1, RD16:1)
#define T2CONbits PIC_BITS(T2CON, T2CKPS0:1, T2CKPS1:1, TMR2ON:1, TOUTPS0:1, TOUTPS1:1, TOUTPS2:1, TOUTPS3:1, :1)
#define SSPCON1bits PIC_BITS(SSPCON1, SSPM0:1, SSPM1:1, SSPM2:1, SSPM3:1, CKP:1, SSPEN:1, SSPOV:1, WCOL:1)
#define SSPSTATbits PIC_BITS(SSPSTAT, BF:1, UA:1, R_NOT_W:1, S:1, P:1, D_NOT_A:1, CKE:1, SMP:1)
#define RCSTAbits PIC_BITS(RCSTA, RX9D:1, OERR:1, FERR:1, ADDEN:1, CREN:1, SREN:1, RX9:1, SPEN:1)
#define TXSTAbits PIC_BITS(TXSTA, TX9D:1, TRMT:1, BRGH:1, SENDB:1, SYNC:1, TXEN:1, TX9:1, CSRC:1)
#define ADCON0bits PIC_BITS(ADCON0, ADON:1, GO:1, CHS0:1, CHS1:1, CHS2:1, CHS3:1, :2)
#define EECON1bits PIC_BITS(EECON1, RD:1, WR:1, WREN:1, WRERR:1, FREE:1, :1, CFGS:1, EEPGD:1)
#define WDTCONbits PIC_BITS(WDTCON, SWDTEN:1, :7)
#endif
