#!/usr/bin/env python3
"""Generate include/pb.h from the per-module variable and prototype lists.

Each module lists the globals it uses in src/<area>.vars:
    <type> <name> <addr-hex> [array-len]      # comment
and the functions it exports in src/<area>.protos (C prototypes).

Variables are merged by address. The same address under several names is
resolved through ALIASES (old name -> kept name); an unresolved clash, or a
variable overlapping another one, is an error so the header never silently
disagrees with a module.

The addresses are the original firmware's; they are kept as comments (the
reconstruction does not need fixed addresses).
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SIZES = {'uint8_t': 1, 'int8_t': 1, 'uint16_t': 2, 'int16_t': 2, 'uint32_t': 4, 'int32_t': 4}

# names used by one module for a variable another module named better
ALIASES = {
    'brew_time_ref': 'bu_stroke_ref',       # r0bc: learned empty brew unit stroke, not a time
    'test_timer_h': None,                   # high byte of step_timer (uint16 at 0x0a4)
}


def load_vars():
    vars_ = {}      # addr -> dict(type, name, len, users, names)
    for f in sorted((ROOT / 'src').glob('*.vars')):
        for ln, line in enumerate(f.read_text().splitlines(), 1):
            line = line.split('#')[0].split('//')[0].strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) < 3 or parts[0] not in SIZES:
                sys.exit(f'{f.name}:{ln}: bad line: {line}')
            typ, name, addr = parts[0], parts[1], int(parts[2], 16)
            n = int(parts[3]) if len(parts) > 3 else 1
            if name in ALIASES:
                if ALIASES[name] is None:
                    continue
                name = ALIASES[name]
            v = vars_.setdefault(addr, {'type': typ, 'name': name, 'len': n, 'users': set(), 'names': set()})
            v['users'].add(f.stem)
            v['names'].add(name)
            if SIZES[typ] * n > SIZES[v['type']] * v['len']:
                v['type'], v['len'] = typ, n
            elif SIZES[typ] == SIZES[v['type']] and typ.startswith('int'):
                v['type'] = typ                                   # signed wins over unsigned
    return vars_


def check(vars_):
    errors = []
    for a, v in vars_.items():
        if len(v['names']) > 1:
            errors.append(f'0x{a:03x}: several names {sorted(v["names"])} ({sorted(v["users"])})')
    spans = sorted((a, a + SIZES[v['type']] * v['len'], v['name']) for a, v in vars_.items())
    for (a0, e0, n0), (a1, e1, n1) in zip(spans, spans[1:]):
        if a1 < e0:
            errors.append(f'0x{a1:03x} {n1} overlaps 0x{a0:03x} {n0} (ends 0x{e0:03x})')
    return errors


def main():
    vars_ = load_vars()
    errors = check(vars_)
    if errors:
        print('\n'.join(errors))
        sys.exit(1)
    protos = []
    for f in sorted((ROOT / 'src').glob('*.protos')):
        protos.append(f'\n/* {f.stem} */')
        protos += [l.rstrip() for l in f.read_text().splitlines() if l.strip()]

    out = [
        '/* Generated by tools/gen_header.py from the .vars and .protos files in src/: do not edit. */',
        '#ifndef PB_H',
        '#define PB_H',
        '',
        '#include <stdint.h>',
        '#include <xc.h>',
        '',
        '/* Globals of the original firmware. The comment gives the original RAM',
        '   address and the modules that use the variable. */',
    ]
    for a in sorted(vars_):
        v = vars_[a]
        arr = f'[{v["len"]}]' if v['len'] > 1 else ''
        decl = f'extern volatile {v["type"]} {v["name"]}{arr};'
        out.append(f'{decl:<52}/* 0x{a:03x} {", ".join(sorted(v["users"]))} */')
    out += protos
    out += ['', '#endif', '']
    (ROOT / 'include' / 'pb.h').write_text('\n'.join(out))

    defs = ['/* Generated by tools/gen_header.py: definitions of the globals in pb.h. */',
            '#include "pb.h"', '']
    for a in sorted(vars_):
        v = vars_[a]
        arr = f'[{v["len"]}]' if v['len'] > 1 else ''
        defs.append(f'volatile {v["type"]} {v["name"]}{arr};')
    (ROOT / 'src' / 'globals.c').write_text('\n'.join(defs) + '\n')

    # host replay tables (host/difftest.c): where each global lived in the
    # original RAM, and the entry address of each exported void(void) function
    tab = ['/* Generated by tools/gen_header.py: replay tables for host/difftest.c. */',
           '#define main pb_main', '#include "pb.h"', '#undef main', '#include "difftest.h"', '',
           'const struct pb_var pb_vars[] = {']
    for a in sorted(vars_):
        v = vars_[a]
        size = SIZES[v['type']] * v['len']
        ref = v['name'] if v['len'] > 1 else '&' + v['name']
        tab.append(f'    {{ 0x{a:03x}, {size}, (volatile void *){ref}, "{v["name"]}" }},')
    tab += ['    { 0, 0, 0, 0 }', '};', '', 'const struct pb_fn pb_fns[] = {']
    for p in protos:
        m = re.match(r'void (?:__interrupt\(\) )?(\w+)\(void\);\s*/\* (0x[0-9a-fA-F]+)', p)
        if m and m.group(1) != 'main':
            tab.append(f'    {{ {m.group(2).lower()}, {m.group(1)}, "{m.group(1)}" }},')
    tab += ['    { 0, 0, 0 }', '};', '']
    (ROOT / 'host' / 'vartab.c').write_text('\n'.join(tab))
    print(f'{len(vars_)} globals, {sum(1 for p in protos if not p.startswith(chr(10)))} prototypes')


if __name__ == '__main__':
    main()
