# Power board symbols proposed by the "comms" analysis (see docs/pb_notes/comms.md)

RAM = {
    # SPI link with the display board
    0xF16: ('spi_rx', 'SPI frame from the display, 11 bytes 0xF16..0xF20 (f_5fbe)'),
    0xF21: ('spi_tx', 'SPI frame to the display, 11 bytes 0xF21..0xF2B (built by f_4d16)'),
    0xEA9: ('spi_idx', 'SPI byte index (f_5fbe), cleared by f_4af4 and on SSPOV/resync'),
    0xEAA: ('spi_last', 'last SPI index (=10), set when 0xB0 received (f_5fbe@5ff2)'),
    0x054: ('spi_resync_ms', '1 ms countdown (TMR2 ISR f_05ca): 15 while a frame is incomplete; at 0 the SSP is re-initialised'),
    0xED7: ('link_timeout', 'display link watchdog: 50 on each valid frame, -1 per r01c.3 tick; at 0 keys are cleared (f_4af4@4be4)'),
    0xE80: ('disp_keys', 'key bitmap from the display (SPI rx[1]), cleared on link loss'),
    0xEA5: ('disp_enc', 'encoder position from the display (SPI rx[2])'),
    0xE8B: ('disp_id', 'SPI rx[3] (constant 0x14 from the display)'),
    0xE8E: ('disp_hour', 'RTC hour from the display, binary (SPI rx[4])'),
    0xE8F: ('disp_min', 'RTC minute (SPI rx[5])'),
    0xE90: ('disp_sec', 'RTC second (SPI rx[6])'),
    0xE81: ('disp_keys_hi', 'SPI rx[7] & 3 (bit1 = encoder push), cleared on link loss'),
    0xE70: ('disp_eecfg', 'display EEPROM config byte (SPI rx[8], 0x65)'),
    0xEDF: ('disp_languages', 'number of languages in the display EEPROM (SPI rx[9])'),
    0xEBC: ('enc_activity', 'set to 30 when the display encoder position changes (f_4af4@4b9a)'),
    0x0F7: ('tx_state', 'scratch: SPI tx[1] machine state being built (f_4d16); also generic temp'),
    0x0F6: ('tx_param1', 'scratch: SPI tx[2] (f_4d16); also generic temp'),
    0x0F8: ('tx_param2', 'scratch: SPI tx[3] (f_4d16); also generic temp'),
    # UART service port
    0xF2C: ('uart_buf', 'UART frame buffer (rx and tx), 0x0A header in, 0xA0 header out'),
    0xEAC: ('uart_rx_idx', 'UART rx index (f_6076)'),
    0xEAD: ('uart_rx_len', 'UART rx length byte (< 0x19)'),
    0xEAE: ('uart_tx_idx', 'UART tx index (f_604c)'),
    0xEAF: ('uart_tx_len', 'UART tx length (len+1)'),
    0x04D: ('uart_rx_to', 'UART inter-byte timeout, 2 x 10 ms (f_6076, f_016a)'),
    0x04E: ('uart_tx_to', 'UART busy hold after a reply, 2 x 10 ms (f_604c, f_016a)'),
    0xE91: ('uart_dest', 'request byte 3: 0x0F = power board, 0xF0 = display-info block (cmd 0x95)'),
    0xE4C: ('io_snapshot', '7 bytes 0xE4C..0xE52: input/output bits packed for UART cmd 0x60/0x80 (f_566e)'),
    0xE5B: ('test_outputs', '4 bytes 0xE5B..0xE5E written by UART cmd 0x80 (remote load test)'),
    0xF0C: ('eeprom_factory', '10 bytes: data EEPROM 0xF6..0xFF copied at boot (f_0980@0b14), read by UART cmd 0xF0'),
    # reply-frame sources (meaning from f_4d16; owned by other areas)
    0x03C: ('machine_state', 'internal machine state = display state number 0x00-0x0F (SPI tx[1])'),
    0x038: ('machine_sub', 'sub-state (SPI tx[2] bits 0-4)'),
    0xE6C: ('menu_item', 'menu item index 0..15 when r026.5 (menu) is set; mapped to states 0x10-0x29'),
    0xF0A: ('menu_value', 'value being edited in the menu (SPI tx[2]) / stats sub-page'),
    0xF0B: ('menu_value2', 'second menu value (minutes for clock items, SPI tx[3] as BCD)'),
    0xEF8: ('test_timer', 'test mode active while != 0; UART cmd 0x80 sets 5'),
    0xE88: ('test_mode', 'test mode number: display state = 0x20 + test_mode (1..5)'),
    0xE86: ('test_param1', 'SPI tx[2] in test modes'),
    0xE71: ('test_step', 'SPI tx[3] in test mode 3 (electric test step)'),
    0xE55: ('cups', 'cups of the current drink: 0 = one, 1 = two (tx param1 bit5)'),
    0xE56: ('drink', 'selected drink 0,2,4,6,8 (tx param2 bits 1-3)'),
    0xE63: ('taste', 'taste field already shifted (tx param2 bits 4-6), 0 while r021.4'),
    0xE79: ('progress', 'progress 0..100 (SPI tx[9])'),
    0xE85: ('fault_hi', 'brew unit fault sub-code (SPI tx[8] bits 2-4)'),
    0x039: ('fault_lo', 'brew unit fault class (SPI tx[8] bits 0-1)'),
    0x0C2: ('settings', 'settings bits: 0 auto-start off, 2 beep, 3 cup light, 4 energy saving, 7 filter (param 0x3F)'),
    0x0DA: ('language', 'language index (param 0x00); tx[5] bits 0-3'),
    0x0DB: ('settings2', 'param 0x01: bit1 = 24 h clock'),
    0x013: ('sensors', 'sensor flags sent as SPI tx[6] unchanged'),
    0x018: ('alarms', 'alarm flags sent as SPI tx[7] (bit5 masked by rf06)'),
    0x019: ('alarms2', 'bits 4-7: tx[7].7 = bit4; tx[8] bits 5-7 = bits 5-7 (bit5 masked by rf05)'),
    0x0CB: ('stat_coffee', '16 bit coffee counter (param 0x67, display stats 0x1A)'),
    0x0CE: ('stat_descale', 'descaling counter (param 0x69, stats 0x1B)'),
    0x0CF: ('stat_water', '32 bit water counter, shown / 2000 (param 0x6A, stats 0x1C)'),
    0x0D3: ('stat_milk', '16 bit milk counter (param 0x6B, stats 0x1E)'),
    0x0D5: ('stat_filter', 'filter counter (param 0x6C, stats 0x1D)'),
    0xEC0: ('eeprom_save_a', 'set to 5 when a parameter 0x00-0x0E is written (save request, block 0xDA..)'),
    0xEC3: ('eeprom_save_b', 'set to 5 when a parameter 0x32-0x41 is written (save request, block 0xB4..)'),
}

FUNCS = {
    0x4ACC: ('comms_init', 'UART 19200 8N2(tx) + SPI slave (SSPCON1=0x15) init, enable SSP and RC interrupts'),
    0x5FBE: ('isr_spi', 'SSP ISR: SPI slave byte exchange, frame sync on 0xB0'),
    0x4AF4: ('comms_update', 'validate the display frame, build the reply, handle UART service frames'),
    0x4D16: ('spi_build_reply', 'build the 11 byte reply frame from the machine state'),
    0x5F7A: ('checksum', 'checksum(ptr r0fc:r0fd, len r0fe, add r0ff): seed 0x55, add (r0ff!=0) or xor'),
    0x2C8E: ('bin_to_bcd', 'W -> (W/10)<<4 | W%10'),
    0x6076: ('isr_uart_rx', 'UART rx ISR: 0x0A header, len < 25, frame ready = r01c.1'),
    0x604C: ('isr_uart_tx', 'UART tx ISR'),
    0x51EA: ('svc_reply_60', 'UART cmd 0x60: I/O snapshot + 4 x 16 bit values'),
    0x5288: ('svc_reply_70', 'UART cmd 0x70: alarms, state, sub-state, temperatures, recipe'),
    0x536C: ('svc_reply_80', 'UART cmd 0x80 reply (odd calls): I/O snapshot'),
    0x53F2: ('svc_reply_81', 'UART cmd 0x80 reply (even calls): analog/diagnostic values'),
    0x545C: ('svc_read_params', 'UART cmd 0x95: read N 32 bit parameters by ID'),
    0x554A: ('svc_reply_f0', 'UART cmd 0xF0: factory bytes (EEPROM 0xF6..0xFF)'),
    0x55C8: ('svc_write_param', 'UART cmd 0x90: write one parameter by ID'),
    0x566E: ('pack_io_snapshot', 'pack r011/r012/r013 bits into 0xE4C..0xE52'),
    0x5704: ('recipe_code', 'current product code 1..0x11 (drink/cups/cappuccino/hot water/milk)'),
    0x583C: ('param_get', 'parameter table read: ID -> 32 bit value'),
    0x5CDC: ('param_set', 'parameter table write: ID, value -> 0 ok / 0xFF bad ID'),
}
