/* Generated by tools/gen_header.py from the .vars and .protos files in src/: do not edit. */
#ifndef PB_H
#define PB_H

#include <stdint.h>
#include <xc.h>

/* Globals of the original firmware. The comment gives the original RAM
   address and the modules that use the variable. */
extern volatile uint8_t adc_last;                   /* 0x00f hw */
extern volatile uint8_t adc_nsamples;               /* 0x010 hw */
extern volatile uint8_t keys;                       /* 0x011 comms, fsm, hw, process, units */
extern volatile uint8_t keys_hi;                    /* 0x012 comms, fsm, hw, units */
extern volatile uint8_t sensors;                    /* 0x013 comms, fsm, hw, process, units */
extern volatile uint8_t alarms;                     /* 0x018 comms, fsm, hw, process, units */
extern volatile uint8_t alarms2;                    /* 0x019 comms, fsm, hw, process, units */
extern volatile uint8_t sysflags;                   /* 0x01b comms, fsm, hw, process, units */
extern volatile uint8_t tickflags;                  /* 0x01c comms, fsm, hw, process, units */
extern volatile uint8_t flags1d;                    /* 0x01d comms, fsm, process, units */
extern volatile uint8_t r01e;                       /* 0x01e comms, fsm, hw, process, units */
extern volatile uint8_t r01f;                       /* 0x01f fsm, hw, process, units */
extern volatile uint8_t heatflags;                  /* 0x020 comms, fsm, hw, process, units */
extern volatile uint8_t flags21;                    /* 0x021 comms, fsm, hw, process, units */
extern volatile uint8_t wait_flags;                 /* 0x022 fsm, process, units */
extern volatile uint8_t ioflags;                    /* 0x023 fsm, hw, process, units */
extern volatile uint8_t sensor_events;              /* 0x024 fsm, hw, process */
extern volatile uint8_t flags25;                    /* 0x025 comms, fsm, hw, process, units */
extern volatile uint8_t flags26;                    /* 0x026 comms, fsm, hw, process, units */
extern volatile uint8_t gateflags2;                 /* 0x027 fsm, hw, process, units */
extern volatile uint8_t flags28;                    /* 0x028 comms, fsm, hw, process, units */
extern volatile uint8_t out_loads;                  /* 0x02a comms, fsm, hw, process, units */
extern volatile uint8_t out_loads2;                 /* 0x02b comms, fsm, hw, units */
extern volatile uint8_t adc_chan;                   /* 0x02c hw */
extern volatile uint8_t keys_count;                 /* 0x02d comms, fsm, hw, process, units */
extern volatile uint8_t pump_period;                /* 0x02e hw, process */
extern volatile uint8_t pump_on_cycles;             /* 0x02f hw, process */
extern volatile uint8_t req_valves;                 /* 0x030 fsm, units */
extern volatile uint8_t req_heatA_sp;               /* 0x031 fsm, units */
extern volatile uint8_t heat2_keepwarm;             /* 0x032 fsm */
extern volatile uint8_t req_heatB_sp;               /* 0x033 fsm, units */
extern volatile uint8_t req_grind;                  /* 0x034 fsm, units */
extern volatile uint8_t req_heat_mode;              /* 0x035 fsm, units */
extern volatile uint8_t pump_state;                 /* 0x037 comms, fsm, hw, process, units */
extern volatile uint8_t mstep;                      /* 0x038 comms, fsm, hw, process, units */
extern volatile uint8_t fault_class;                /* 0x039 comms, fsm, hw, process, units */
extern volatile uint8_t heatA_state;                /* 0x03a hw, units */
extern volatile uint8_t heatB_state;                /* 0x03b hw, units */
extern volatile uint8_t mstate;                     /* 0x03c comms, fsm, hw, process, units */
extern volatile uint8_t bu_zone;                    /* 0x03d fsm, units */
extern volatile uint8_t bu_state;                   /* 0x03e fsm, hw, units */
extern volatile uint8_t grind_state;                /* 0x03f fsm, hw, units */
extern volatile uint8_t loop_tasks;                 /* 0x040 comms, fsm, hw */
extern volatile uint8_t ee_flags;                   /* 0x042 fsm, hw */
extern volatile uint8_t key_edges;                  /* 0x043 fsm, hw, process, units */
extern volatile uint8_t keys_hi_edges;              /* 0x044 fsm, hw, process */
extern volatile uint8_t sensor_edges;               /* 0x045 hw, process */
extern volatile uint8_t portd_tmp;                  /* 0x046 hw */
extern volatile uint8_t portd_req;                  /* 0x047 hw */
extern volatile uint8_t ee_write_timer;             /* 0x049 hw */
extern volatile uint8_t zc_watchdog;                /* 0x04a hw */
extern volatile uint8_t startup_timer;              /* 0x04c hw */
extern volatile uint8_t uart_rx_to;                 /* 0x04d comms, hw */
extern volatile uint8_t uart_tx_to;                 /* 0x04e comms, hw */
extern volatile uint8_t sensor_debounce;            /* 0x04f hw */
extern volatile uint8_t pump_pulse_cnt;             /* 0x050 hw */
extern volatile uint8_t ac_sample_timer;            /* 0x051 hw */
extern volatile uint8_t adc_start_timer;            /* 0x052 hw */
extern volatile uint8_t r053;                       /* 0x053 hw */
extern volatile uint8_t spi_resync_timer;           /* 0x054 comms, hw */
extern volatile uint8_t r055;                       /* 0x055 hw */
extern volatile uint8_t div_10ms;                   /* 0x056 hw */
extern volatile uint8_t mains_100ms_cnt;            /* 0x057 hw */
extern volatile uint8_t zc_ticks;                   /* 0x058 hw */
extern volatile uint8_t gate_timer;                 /* 0x059 hw */
extern volatile uint8_t fire_timer;                 /* 0x05a hw */
extern volatile uint16_t bu_target_l;               /* 0x05b units */
extern volatile uint16_t heatA_power;               /* 0x05d hw, units */
extern volatile uint16_t heater1_power_cur;         /* 0x05f hw */
extern volatile uint16_t heatB_power;               /* 0x061 hw, units */
extern volatile uint16_t heater2_power_cur;         /* 0x063 hw */
extern volatile uint16_t req_bu_target;             /* 0x065 fsm, units */
extern volatile uint16_t req_pump_vol;              /* 0x067 fsm, units */
extern volatile uint16_t pump_cnt_l;                /* 0x06b comms, fsm, process, units */
extern volatile uint16_t bu_pos;                    /* 0x06d comms, fsm, process, units */
extern volatile uint16_t heater1_window;            /* 0x06f hw */
extern volatile uint16_t heater2_window;            /* 0x071 hw */
extern volatile uint8_t crc_lo;                     /* 0x090 hw */
extern volatile uint8_t crc_hi;                     /* 0x091 hw */
extern volatile uint16_t target_qty;                /* 0x092 fsm, process */
extern volatile uint16_t target_qty_total;          /* 0x094 fsm, process */
extern volatile uint16_t r096;                      /* 0x096 fsm, process, units */
extern volatile uint16_t nowater_cnt_l;             /* 0x098 fsm, process, units */
extern volatile uint16_t zc_period;                 /* 0x09a hw */
extern volatile uint16_t r09c;                      /* 0x09c hw */
extern volatile uint16_t ready_timer;               /* 0x09e fsm, hw, process */
extern volatile uint16_t ccpr_now;                  /* 0x0a0 hw */
extern volatile uint16_t uptime_100ms;              /* 0x0a2 fsm, hw, process, units */
extern volatile uint16_t step_timer;                /* 0x0a4 fsm, hw, process, units */
extern volatile uint16_t ccpr_prev;                 /* 0x0a6 hw */
extern volatile uint16_t grounds_timer;             /* 0x0a8 fsm, hw */
extern volatile uint16_t autooff_time;              /* 0x0aa fsm, hw */
extern volatile uint16_t adc_sum[2];                /* 0x0ac hw */
extern volatile uint8_t set_hardness;               /* 0x0b4 comms, fsm, hw, process */
extern volatile uint8_t grind_hist_a;               /* 0x0b5 comms, hw, process */
extern volatile uint8_t set_b2;                     /* 0x0b6 comms, hw, process */
extern volatile uint8_t set_b3;                     /* 0x0b7 comms, hw, process */
extern volatile uint8_t grind_hist_b;               /* 0x0b8 comms, hw, process */
extern volatile uint8_t set_b5;                     /* 0x0b9 comms, hw, process */
extern volatile uint8_t grind_hist_c;               /* 0x0ba comms, hw, process */
extern volatile uint8_t set_b7;                     /* 0x0bb comms, hw, process */
extern volatile uint16_t bu_stroke_ref;             /* 0x0bc comms, fsm, hw, process */
extern volatile uint8_t grind_center;               /* 0x0be comms, hw, process */
extern volatile uint8_t set_fault;                  /* 0x0bf comms, hw, process */
extern volatile uint8_t set_temperature;            /* 0x0c0 comms, fsm, hw, process, units */
extern volatile uint8_t set_autooff;                /* 0x0c1 comms, fsm, hw, process */
extern volatile uint8_t settings;                   /* 0x0c2 comms, fsm, hw, process, units */
extern volatile uint8_t set_autostart_h;            /* 0x0c3 comms, hw, process */
extern volatile uint8_t set_autostart_m;            /* 0x0c4 comms, hw, process */
extern volatile uint32_t water_since_descale;       /* 0x0c5 comms, fsm, hw, units */
extern volatile uint8_t grounds_count;              /* 0x0c9 comms, fsm, hw, units */
extern volatile uint8_t cnt_ca;                     /* 0x0ca comms, hw, units */
extern volatile uint16_t stat_coffee;               /* 0x0cb comms, hw, units */
extern volatile uint8_t cnt_e;                      /* 0x0cd comms, hw */
extern volatile uint8_t stat_descale;               /* 0x0ce comms, fsm, hw */
extern volatile uint32_t stat_water;                /* 0x0cf comms, hw, units */
extern volatile uint16_t stat_milk;                 /* 0x0d3 comms, hw, units */
extern volatile uint8_t stat_filter;                /* 0x0d5 comms, hw, process */
extern volatile uint32_t water_since_filter;        /* 0x0d6 comms, fsm, hw, process, units */
extern volatile uint8_t language;                   /* 0x0da comms, fsm, hw, process */
extern volatile uint8_t settings2;                  /* 0x0db comms, fsm, hw, process, units */
extern volatile uint16_t qty_my;                    /* 0x0dc comms, hw, process */
extern volatile uint16_t qty_espresso;              /* 0x0de comms, hw, process */
extern volatile uint16_t qty_standard;              /* 0x0e0 comms, hw, process */
extern volatile uint16_t qty_long;                  /* 0x0e2 comms, hw, process */
extern volatile uint16_t qty_extralong;             /* 0x0e4 comms, hw, process */
extern volatile uint8_t qty5_b;                     /* 0x0e6 comms, fsm, hw */
extern volatile uint16_t qty_hotwater;              /* 0x0e7 comms, fsm, hw, process */
extern volatile uint16_t qty_cappu_coffee;          /* 0x0e9 comms, hw, process */
extern volatile uint16_t qty_milk_0;                /* 0x0eb comms, fsm, hw, process */
extern volatile uint16_t qty9;                      /* 0x0ed comms, hw */
extern volatile uint16_t qty_milk_1;                /* 0x0ef comms, fsm, hw, process */
extern volatile uint16_t qty11;                     /* 0x0f1 comms, hw */
extern volatile uint16_t qty_milk_2;                /* 0x0f3 comms, fsm, hw, process */
extern volatile uint8_t io_snapshot[7];             /* 0xe4c comms */
extern volatile uint8_t grind_avg;                  /* 0xe53 process */
extern volatile uint8_t milk_prog_slot;             /* 0xe54 fsm, process */
extern volatile uint8_t cups;                       /* 0xe55 comms, process */
extern volatile uint8_t drink;                      /* 0xe56 comms, hw, process */
extern volatile uint8_t grind_1cup;                 /* 0xe57 process */
extern volatile uint8_t grind_2cup;                 /* 0xe58 process */
extern volatile uint8_t flow_win;                   /* 0xe59 units */
extern volatile uint8_t enc_step;                   /* 0xe5a process */
extern volatile uint8_t test_cmd;                   /* 0xe5b comms, units */
extern volatile uint8_t test_arg0;                  /* 0xe5c comms, units */
extern volatile uint8_t test_arg1;                  /* 0xe5d comms, units */
extern volatile uint8_t test_arg2;                  /* 0xe5e comms, units */
extern volatile uint8_t temp_coffee;                /* 0xe5f comms, fsm, hw, process, units */
extern volatile uint8_t heatA_regul;                /* 0xe60 units */
extern volatile uint8_t temp_steam;                 /* 0xe61 comms, fsm, hw, process, units */
extern volatile uint8_t ee_idx;                     /* 0xe62 hw */
extern volatile uint8_t taste;                      /* 0xe63 comms, hw, process */
extern volatile uint8_t eco_level;                  /* 0xe65 fsm */
extern volatile uint8_t ee_copy;                    /* 0xe66 hw */
extern volatile uint8_t brew_pwr_idx;               /* 0xe67 units */
extern volatile uint8_t flow_avg;                   /* 0xe68 hw, units */
extern volatile uint8_t flow_sum;                   /* 0xe69 units */
extern volatile uint8_t lang_preview;               /* 0xe6a comms, process */
extern volatile uint8_t menu_level;                 /* 0xe6b process */
extern volatile uint8_t menu_item;                  /* 0xe6c comms, process */
extern volatile uint8_t re6f;                       /* 0xe6f hw */
extern volatile uint8_t disp_eecfg;                 /* 0xe70 comms */
extern volatile uint8_t test_echo;                  /* 0xe71 comms, units */
extern volatile uint8_t saved_mstep;                /* 0xe72 fsm, hw, process */
extern volatile uint8_t saved_mstate;               /* 0xe73 fsm, hw, process */
extern volatile uint8_t sensor_sample;              /* 0xe76 hw */
extern volatile uint8_t re77;                       /* 0xe77 comms */
extern volatile uint8_t re78;                       /* 0xe78 comms */
extern volatile uint8_t progress;                   /* 0xe79 comms, units */
extern volatile uint8_t flow_watchdog;              /* 0xe7a hw, units */
extern volatile uint8_t ac_sample_delay;            /* 0xe7b hw */
extern volatile uint8_t halfcycles_100ms;           /* 0xe7c hw */
extern volatile uint8_t burst_fire_delay;           /* 0xe7d hw */
extern volatile uint8_t wait_snap;                  /* 0xe7f units */
extern volatile uint8_t disp_keys;                  /* 0xe80 comms, hw */
extern volatile uint8_t disp_keys_hi;               /* 0xe81 comms, hw */
extern volatile uint8_t cappu_phase;                /* 0xe83 fsm, process, units */
extern volatile uint8_t brew_phase;                 /* 0xe84 fsm, process */
extern volatile uint8_t fault_step;                 /* 0xe85 comms, fsm, hw, process, units */
extern volatile uint8_t test_step;                  /* 0xe86 comms, fsm, hw, units */
extern volatile uint8_t re87;                       /* 0xe87 fsm */
extern volatile uint8_t test_mode;                  /* 0xe88 comms, fsm, units */
extern volatile uint8_t standby_flag;               /* 0xe89 process */
extern volatile uint8_t wake_reason;                /* 0xe8a hw */
extern volatile uint8_t disp_id;                    /* 0xe8b comms */
extern volatile uint8_t disp_hour;                  /* 0xe8e comms, hw, process */
extern volatile uint8_t disp_min;                   /* 0xe8f comms, hw, process */
extern volatile uint8_t disp_sec;                   /* 0xe90 comms, hw, process */
extern volatile uint8_t uart_dest;                  /* 0xe91 comms */
extern volatile uint8_t ac_inputs;                  /* 0xe92 hw */
extern volatile uint8_t ac_toggle;                  /* 0xe93 hw */
extern volatile uint8_t re95;                       /* 0xe95 fsm */
extern volatile uint8_t bu_delay_down;              /* 0xe96 fsm, hw, units */
extern volatile uint8_t bu_delay_up;                /* 0xe97 fsm, hw, units */
extern volatile uint8_t progress_hold;              /* 0xe99 hw, units */
extern volatile uint8_t ready_countdown;            /* 0xe9a hw, process */
extern volatile uint8_t heatB_hold;                 /* 0xe9b hw, units */
extern volatile uint8_t heatA_hold;                 /* 0xe9c hw, units */
extern volatile uint8_t re9d;                       /* 0xe9d hw */
extern volatile uint8_t bu_softstart;               /* 0xe9e fsm, hw, units */
extern volatile uint8_t bu_runon;                   /* 0xe9f fsm, hw, units */
extern volatile uint8_t wake_timer;                 /* 0xea0 hw */
extern volatile uint8_t zc_cnt50;                   /* 0xea2 hw */
extern volatile uint8_t zc_cnt60;                   /* 0xea3 hw */
extern volatile uint8_t disp_enc;                   /* 0xea5 comms, process */
extern volatile uint8_t enc_last;                   /* 0xea6 process */
extern volatile uint8_t heatA_req;                  /* 0xea7 hw, units */
extern volatile uint8_t heatB_req;                  /* 0xea8 hw, units */
extern volatile uint8_t spi_idx;                    /* 0xea9 comms, hw */
extern volatile uint8_t spi_last;                   /* 0xeaa comms */
extern volatile uint8_t zc_valid_cnt;               /* 0xeab hw */
extern volatile uint8_t uart_rx_idx;                /* 0xeac comms, hw */
extern volatile uint8_t uart_rx_len;                /* 0xead comms */
extern volatile uint8_t uart_tx_idx;                /* 0xeae comms */
extern volatile uint8_t uart_tx_len;                /* 0xeaf comms */
extern volatile uint8_t zc_lost_cnt;                /* 0xeb0 hw */
extern volatile uint8_t zc_ok_cnt;                  /* 0xeb1 hw */
extern volatile uint8_t reb4;                       /* 0xeb4 hw */
extern volatile uint8_t reb5;                       /* 0xeb5 comms, hw, process */
extern volatile uint8_t clean_ticks;                /* 0xeb6 process, units */
extern volatile uint8_t preheat_delay;              /* 0xeb7 hw, process */
extern volatile uint8_t reb8;                       /* 0xeb8 hw, units */
extern volatile uint8_t reb9;                       /* 0xeb9 hw */
extern volatile uint8_t reba;                       /* 0xeba hw, process */
extern volatile uint8_t rebb;                       /* 0xebb hw */
extern volatile uint8_t enc_activity;               /* 0xebc comms, process */
extern volatile uint8_t rebd;                       /* 0xebd fsm, hw, process */
extern volatile uint8_t grounds_out_timer;          /* 0xebe fsm */
extern volatile uint8_t milk_end_timer;             /* 0xebf fsm, process */
extern volatile uint8_t ee_save_req_c0;             /* 0xec0 comms, fsm, process */
extern volatile uint8_t flow_win_timer;             /* 0xec1 units */
extern volatile uint8_t flow_start_delay;           /* 0xec2 hw, units */
extern volatile uint8_t ee_save_req_c3;             /* 0xec3 comms, fsm, process, units */
extern volatile uint8_t rec4;                       /* 0xec4 hw, process */
extern volatile uint8_t rec5;                       /* 0xec5 fsm, process */
extern volatile uint8_t lang_cycle_timer;           /* 0xec6 hw, process */
extern volatile uint8_t lang_cycle_timer2;          /* 0xec7 hw, process */
extern volatile uint8_t flow_watchdog2;             /* 0xec8 fsm, hw, units */
extern volatile uint8_t bu_idle;                    /* 0xec9 hw, units */
extern volatile uint8_t active_timer;               /* 0xeca fsm, hw */
extern volatile uint8_t recb;                       /* 0xecb comms, process */
extern volatile uint8_t grind_dose;                 /* 0xecc fsm, process */
extern volatile uint8_t grind_dose_hi;              /* 0xecd process */
extern volatile uint8_t grind_dose_lo;              /* 0xece process */
extern volatile uint8_t recf;                       /* 0xecf hw */
extern volatile uint8_t motor_run_timer;            /* 0xed0 fsm */
extern volatile uint8_t cappu_toggle_win;           /* 0xed1 fsm, hw, process */
extern volatile uint8_t grind_ticks;                /* 0xed2 units */
extern volatile uint8_t red3;                       /* 0xed3 hw */
extern volatile uint8_t long_press_ms;              /* 0xed4 process */
extern volatile uint8_t prog_press_timer;           /* 0xed5 comms, hw, process */
extern volatile uint8_t red6;                       /* 0xed6 fsm, hw */
extern volatile uint8_t link_timeout;               /* 0xed7 comms, hw */
extern volatile uint8_t red8;                       /* 0xed8 hw */
extern volatile uint8_t red9;                       /* 0xed9 fsm, process, units */
extern volatile uint8_t reda;                       /* 0xeda comms, hw */
extern volatile uint8_t test_key_sel;               /* 0xedc hw, units */
extern volatile int8_t temp_coffee_slope;           /* 0xede hw, units */
extern volatile uint8_t disp_languages;             /* 0xedf comms, process */
extern volatile uint8_t menu_value_max;             /* 0xee0 process */
extern volatile uint8_t ree1;                       /* 0xee1 units */
extern volatile uint8_t ac_inputs_prev;             /* 0xee3 hw */
extern volatile uint8_t temp_an1_prev;              /* 0xee4 hw */
extern volatile uint8_t ree5;                       /* 0xee5 hw */
extern volatile uint8_t heatA_last_sp;              /* 0xee6 units */
extern volatile uint8_t heatB_last_sp;              /* 0xee7 units */
extern volatile uint8_t div_10s;                    /* 0xee8 hw */
extern volatile uint8_t div_1s;                     /* 0xee9 hw */
extern volatile uint8_t reea;                       /* 0xeea hw */
extern volatile uint8_t reeb;                       /* 0xeeb fsm */
extern volatile uint8_t ready_idle;                 /* 0xeec fsm */
extern volatile uint8_t reed;                       /* 0xeed fsm, hw */
extern volatile uint8_t reee;                       /* 0xeee hw */
extern volatile uint8_t ref0;                       /* 0xef0 fsm, hw */
extern volatile uint8_t eco_timer;                  /* 0xef2 fsm, hw */
extern volatile uint8_t ref3;                       /* 0xef3 fsm, hw */
extern volatile uint8_t descale_timer;              /* 0xef4 fsm, process */
extern volatile uint8_t bu_idle_delay;              /* 0xef5 fsm, hw, units */
extern volatile uint8_t energy_timer;               /* 0xef6 comms, hw, process */
extern volatile uint8_t ref7;                       /* 0xef7 hw */
extern volatile uint8_t test_timer;                 /* 0xef8 comms, fsm, hw, units */
extern volatile uint8_t ref9;                       /* 0xef9 hw */
extern volatile uint8_t refa;                       /* 0xefa comms, hw, process */
extern volatile uint8_t refb;                       /* 0xefb hw */
extern volatile uint8_t refc;                       /* 0xefc hw, process */
extern volatile uint8_t menu_timeout;               /* 0xefd hw, process */
extern volatile uint8_t refe;                       /* 0xefe process */
extern volatile uint8_t reff;                       /* 0xeff process */
extern volatile uint8_t milk_timer;                 /* 0xf00 comms, process */
extern volatile uint8_t rf01;                       /* 0xf01 hw */
extern volatile uint8_t activity_timer;             /* 0xf02 hw, process */
extern volatile uint8_t rf03;                       /* 0xf03 fsm, hw */
extern volatile uint8_t rf04;                       /* 0xf04 hw */
extern volatile uint8_t less_coffee_timer;          /* 0xf05 comms, hw, process */
extern volatile uint8_t beans_alarm_timer;          /* 0xf06 comms, hw, process */
extern volatile uint8_t rf07;                       /* 0xf07 hw, process */
extern volatile uint8_t menu_value;                 /* 0xf0a comms, process */
extern volatile uint8_t menu_minutes;               /* 0xf0b comms, process */
extern volatile uint8_t ee_factory[10];             /* 0xf0c comms, hw */
extern volatile uint8_t spi_rx[11];                 /* 0xf16 comms */
extern volatile uint8_t spi_tx[11];                 /* 0xf21 comms */
extern volatile uint8_t uart_buf[25];               /* 0xf2c comms */
extern volatile uint8_t ee_buf[29];                 /* 0xf45 hw */

/* comms */
void comms_init(void); /* 0x4acc comms_init */
void comms_update(void); /* 0x4af4 comms_update */
void spi_build_reply(void); /* 0x4d16 spi_build_reply */
uint8_t checksum(const volatile uint8_t *buf, uint8_t len, uint8_t add); /* 0x5f7a checksum */
void isr_spi(void); /* 0x5fbe isr_spi */
void isr_uart_rx(void); /* 0x6076 isr_uart_rx */
void isr_uart_tx(void); /* 0x604c isr_uart_tx */
void service_dispatch(void); /* 0x4bf4 comms_update (UART half) */
void svc_reply_60(void); /* 0x51ea svc_reply_60 */
void svc_reply_70(void); /* 0x5288 svc_reply_70 */
void svc_reply_80(void); /* 0x536c svc_reply_80 */
void svc_reply_81(void); /* 0x53f2 svc_reply_81 */
void svc_read_params(void); /* 0x545c svc_read_params */
void svc_reply_f0(void); /* 0x554a svc_reply_f0 */
void svc_write_param(void); /* 0x55c8 svc_write_param */
void pack_io_snapshot(void); /* 0x566e pack_io_snapshot */
uint8_t recipe_code(void); /* 0x5704 recipe_code */
uint32_t param_get(uint16_t id); /* 0x583c param_get */
uint8_t param_set(uint16_t id, uint32_t v); /* 0x5cdc param_set */

/* fsm */
void state_control(void); /* 0x3186 state_control */
void monitor_faults(void); /* 0x803e monitor_faults */

/* hw */
void main(void);                     /* 0x6100 main */
void __interrupt() isr(void);        /* 0x6FCE isr */
void timers_init(void);              /* 0x0040 timers_init */
void zc_watch_init(void);            /* 0x0158 zc_watch_init */
void timebase(void);                 /* 0x016A timebase */
void adc_init(void);                 /* 0x0DA6 adc_init */
void adc_task(void);                 /* 0x0DD8 adc_task */
void isr_adc(void);                  /* 0x0EAE isr_adc */
void inputs_clear(void);             /* 0x61A8 inputs_clear */
void inputs_task(void);              /* 0x6208 inputs_task */
void outputs_task(void);             /* 0x6302 outputs_task */
void power_task(void);               /* 0x4998 power_task */
void ee_load(void);                  /* 0x0980 ee_load */
void ee_save_task(void);             /* 0x0B3A ee_save_task */
void recA_defaults(uint8_t all);     /* 0x451A recA_defaults (menu_item_apply passes != 0xFF to keep language/options) */

/* process */
void machine_control(void); /* 0x10c0 machine_control */
void grind_history_update(uint16_t stroke); /* 0x2be6 grind_history_update (stroke passed in r0f5:r0f6) */
void grind_dose_compute(void); /* 0x2718 grind_dose_compute */
uint8_t bin_to_bcd(uint8_t v); /* 0x2c8e bin_to_bcd */
void menu_keys(void); /* 0x241c part of machine_control (menu keys and encoder) */
void menu_item_open(void); /* 0x2cb8 menu_item_open */
void menu_item_apply(void); /* 0x2dee menu_item_apply */
void menu_time_inc(uint8_t which); /* 0x3002 menu_time_inc */
void menu_time_dec(uint8_t which); /* 0x3044 menu_time_dec */

/* units */
uint8_t heatB_demand(void); /* 0x76de heatB_demand */
uint8_t heatA_demand(void); /* 0x7716 heatA_demand */
void heat_power_mgr(void); /* 0x7106 heat_power_mgr */
void heatB_ctrl(void); /* 0x72bc heatB_ctrl */
void heatA_ctrl(void); /* 0x7464 heatA_ctrl */
void brew_power_adapt(void); /* 0x7768 brew_power_adapt */
void pump_ctrl(void); /* 0x7b90 pump_ctrl */
void grinder_ctrl(void); /* 0x7dd2 grinder_ctrl */
void bu_motor(void); /* 0x7980 bu_motor */
void wait_snapshot(void); /* 0x7e58 wait_snapshot */
void step_sequencer(void); /* 0x7e86 step_sequencer */
void progress_update(void); /* 0x6b6e progress_update */
void counters_update(void); /* 0x6832 counters_update */
void test1_nop(void); /* 0x6386 test1_nop */
void test5_select(void); /* 0x6388 test5_select */
void test2_load(void); /* 0x63cc test2_load */
void test4_auto(void); /* 0x64f8 test4_auto */
void test3_remote(void); /* 0x65c0 test3_remote */

#endif
