
// Don't know what it does exactly yet
void Coralie(void)
{
	CLRWDT();

	if (ENTRY_DATA_UNK1 & 0x04)
	{
		CLR(ENTRY_DATA_UNK1, 2);
		if (SSP_PACKET_UNK1 & 0x80 && SSP_PACKET_DATA_18 == 0x01)
		{
			SET(ENTRY_DATA_UNK1, 4);
			POWEBOARD_COM_INIT(0x00);
			USART_LOGIC_UNK26 = 0x3c;
		}
		else
		{
			CLR(ENTRY_DATA_UNK1, 4);
			POWERBOARD_COM_INIT(0xff);
		}
	}

	if (ENTRY_DATA_UNK3 & 0x10)
	{
		USART_LOGIC_UNK27 = 0x00;
		USART_LOGIC_UNK28 = 0x00;
		USART_LOGIC_UNK29 = 0xd0;
		Caroline();
		if (Eloise())
		{
			SSP_PACKET_DATA_17_PARAM = PACKET_BUFFER[0];
			SSP_PACKET_DATA_16_PARAM = PACKET_BUFFER[1];
			SSP_PACKET_DATA_15_PARAM = PACKET_BUFFER[2];
		}
	}

	if ((TIMER1_UNK4 & 0x3f) != 0x11 && TIMER1_UNK4 & 0x80 && SSP_PACKET_UNK1 & 0x08 && SSP_PACKET_DATA_18 == 0x01)
	{
		// Wait ~8 cycles
		USART_LOGIC_UNK30 = 0x00;
		do { USART_LOGIC_UNK30 += 1; } while(USART_LOGIC_UNK30 < 0x08);

		USART_PACKET_CHECKSUM = Evelise(0x3b);
		if (USART_PACKET_CHECKSUM < 0x18)
		{
			USART_LOGIC_UNK2 = Evelise(USART_LOGIC_UNK7);
			if (USART_LOGIC_UNK2 < 0x3c)
			{
				SSP_PACKET_DATA_15_PARAM = USART_LOGIC_UNK6;
				SSP_PACKET_DATA_16_PARAM = USART_LOGIC_UNK7;
				SSP_PACKET_DATA_17_PARAM = 0x00;
				SET(SSP_PACKET_DATA_18_BITCOND, 6);
				PACKET_BUFFER[2] = SSP_PACKET_DATA_15_PARAM;
				PACKET_BUFFER[1] = SSP_PACKET_DATA_16_PARAM;
				PACKET_BUFFER[0] = SSP_PACKET_DATA_17_PARAM;
				PACKET_BUFFER[7] = 0x00;
				SSP_PACKET_DATA_12 = 0x00;
				SSP_PACKET_DATA_18_MASK = 0x00;
				SSP_PACKET_DATA_18_TMP = 0xd0;
				Cecile();
			}
		}
	}

	if (SSP_PACKET_DATA_18_BITCOND & 0x20)
		if (HW_INIT2_UNK7)
			HW_INIT2_UNK7 = 0x3c;
	else
		HW_INIT2_UNK7 = 0x3c;
}
