// Main loop sub functions

// This work only on shadowed vars
void Estelle(void)
{
	ESTELLE_UNK1 = 0x00;
	ESTELLE_UNK2 = 0x00;

	do
	{
		MLOGIC_SUB2_UNK2 >>= 1;
		MLOGIC_SUB2_UNK1 >>= 1;

		if (MLOGIC_SUB2-UNK1 != 0)
			// why?
			if (ENTRY_SUB2_UNK1 + EVELISE_UNK1 < ENTRY_SUB2_UNK1)
				ESTELLE_UNK2 = ESTELLE_UNK2 + EVELISE_UNK1 + 1
			else
				ESTELE_UNK2 = ESTELLE_UNK2 + EVELISE_UNK1

		ENTRY2_SUB2_UNK1 <<= 1;
		EVELISE_UNK1 <<= 1;
	} while (MLOGIC_SUB2_UNK1 | MLOGIC_SUB2_UNK2);

	return 0;
}

// Don't know what this does yet
void Clara(char param)
{
	INIT_ST1_UNK1 = param;
	MLOGIC_SUB2_UNK1 = 0x64;
	MLOGIC_SUB2_UNK2 = 0x00;
	ENTRY_SUB2_UNK1 = USART_LOGIC_UNK24;

	Estelle();

	ENTRY_SUB2_UNK1 = INIT_ST1_UNK1;
	EVELISE_UNK1 = 0x00;
	ENTRY_SUB2_UNK1 += ESTELLE_UNK1;
	EVELISE_UNK1 += 1;
	EVELISE_UNK1 += EVELISE_UNK2;
	MLOGIC_SUB2_UNK1 = 0x14;
	MLOGIC_SUB2_UNK2 = 0x00;

	Estelle();

	ESTELLE_UNK1 = 0x14;
	ESTELLE_UNK2 += 1;
	CLARA_UNK5 = ESTELLE_UNK1;
	CLARA_UNK6 = ESTELLE_UNK2;
	CLARA_UNK3 = CLARA_UNK5 & 0xf0;
	CLARA_UNK4 = CLARA_UNK6 & 0xff;
	CLARA_UNK1 = CLARA_UNK5 & 0x0f;

	INIT_ST1_UNK3 = 0x00;
	USART_LOGIC_UNK27 = CLARA_UNK3;
	USART_LOGIC_UNK28 = CLARA_UNK4;
	USART_LOGIC_UNK29 = 0xa0;
	Caroline();

	// First loop
	CHECKSUM_UNK1 = 0x00;
	goto clara_midloop_1;
	do
	{
		CHECKSUM_UNK2 = PACKET_BUFFER[CLARA_UNK1+CHECKSUM_UNK1];
		CLARA_ARRAY[INIT_ST1_UNK3] = CHECKSUM_UNK2;

		CHECKSUM_UNK1 += 1;
		INIT_ST1_UNK3 = 0x00;

clara_midloop_1: // this is ugly

		ENTRY_SUB2_UNK1;
		EVELISE_UNK1 = 0x00;
		ENTRY_SUB2_UNK1 -= CLARA_UNK1;
		EVELISE_UNK1 -= 1;
		CHECKSUM_UNK2 = CHECKSUM_UNK1;
		ADELE_UNK1 = 0x00;
		MLOGIC_SUB2_UNK1 = ADELE_UNK1 ^ 0x80;
	} while(!(MLOGIC_SUB2_UNK1 - EVELISE_UNK1 ^ 0x80) || CHECKSUM_UNK2 < ENTRY_SUB2_UNK1);

	// second loop
	INIT_ST1_UNK2 = 0x00;
	INIT_ST1_UNK2 += 1;
	do
	{
		CHECKSUM_UNK2 = INIT_ST1_UNK2;
		ADELE_UNK1 = 0x00;
		CHECKSUM_UNK2 = CHECKSUM_UNK2 & 0xf0 >> 4 | CHECKSUM_UNK2 & 0x0f << 4;
		ADELE_UNK1 = ADELE_UNK1 & 0xf0 >> 4 | ADELE_UNK1 & 0x0f << 4;
		ADELE_UNK1 & 0xf0;
		ADELE_UNK1 |= CHECKSUM_UNK2 & 0x0f;
		CHECKSUM_UNK2 += CLARA_UNK3;
		ADELE_UNK1 += 1;
		ADELE_UNK1 += CLARA_UNK4;
		USART_LOGIC_UNK27 = CHECKSUM_UNK2;
		USART_LOGIC_UNK28 = ADELE_UNK1;
		USART_LOGIC_UNK29 = 0xa0;
		Caroline();

		CHECKSUM_UNK1 = 0x00;
		do
		{
			CHECKSUM_UNK2 = PACKET_BUFFER[CHECKSUM_UNK1];
			CLARA_ARRAY[INIT_ST1_UNK3] = CHECKSUM_UNK2;

			if (INIT_ST1_UNK3 != CLARA_UNK2)
			{
				CHECKSUM_UNK1 += 1;
				INIT_ST1_UNK3 += 1;
			}
		} while(INIT_ST1_UNK3 == CLARA_UNK2 || 0x10 < CHECKSUM_UNK1);

		INIT_ST1_UNK2 += 1;

	} while( CLARA_UNK2 < INIT_ST1_UNK3);
}
